main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name='home'),
path('about/', views.about, name='about'),
path('trails/', views.trails_index, name ='index'),
path('trails/<int:trail_id>/', views.trails_detail, name='detail'),
path('trails/create/',views.TrailCreate.as_view(), name='trails_create'),
path('trails/<int:pk>/update/', views.TrailUpdate.as_view(), name= 'trails_update'),
path('trails/<int:pk>/delete/', views.TrailDelete.as_view(), name = 'trails_delete'),
path('trails/<int:trail_id>/add_maintaining/', views.add_maintaining, name='add_maintaining')
]

trailcollectorv4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from audioop import reverse
from django.db import models
from django.urls import reverse

TASKS = (
    ('B', 'Blaze repairt'),
    ('C', 'Cut branches'),
    ('G','Garbage collecting')
)

# Create your models here.
class Trail (models.Model):
    name = models.CharField(max_length=100)
    terrian = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    length= models.IntegerField()

    def __str__(self):
        return self.name
    def get_absolute_url (self):
       return reverse ('detail', kwargs={'trail_id': self.id})


class Maintaining(models.Model):
    date = models.DateField("Maintaining Time")
    task = models.CharField(
      max_length=1,
      choices=TASKS,
      default=TASKS[0][0]
  )
    
    trail = models.ForeignKey(Trail, on_delete=models.CASCADE)
    def __str__(self):
      return f"{self.get_task_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Maintaining

class MaintainingForm(ModelForm):
  class Meta:
    model = Maintaining
    fields = ['date', 'task']  

main_app/views.py
from django.shortcuts import render,redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from main_app.models import Trail
from .forms import MaintainingForm

class TrailCreate(CreateView) :
    model = Trail
    fields = '__all__'

class TrailUpdate(UpdateView) :
    model= Trail
    fields =['terrian', 'description','length'] 
    context_object_name = 'trail'

class TrailDelete(DeleteView) :
    model= Trail
    success_url ='/trails/' 
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def trails_index(request):
    trails = Trail.objects.all()
    return render(request,'trails/index.html', {'trails': trails})
def trails_detail(request, trail_id):
    trail = Trail.objects.get(id=trail_id)
    maintaining_form = MaintainingForm()
    return render(request, 'trails/detail.html', {
        'trail': trail, 'maintaining_form': maintaining_form})

def add_maintaining(request, trail_id):
  form = MaintainingForm(request.POST)

  if form.is_valid():
    maintaining = form.save(commit=False)
    maintaining.trail_id = trail_id
    maintaining.save()

  return redirect('detail', trail_id=trail_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>This app is about The Hiking Trails in Ontario</h1>
<hr />
<p>Join us for next hiking trip!!!</p>

{% endblock %}

  
  

  

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>The trail Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;TrailCollector</a></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'trails_create' %}">Add a Trail</a></li>
            <li><a href="{% url 'index' %}">All Trails</a></li>
            
            
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Trails &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home </h1>

{% endblock %}

main_app/templates/main_app/trail_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Trail</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value=" Delete!" class="btn">
    <a href="{% url 'detail' trail.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/trail_form.html
{% extends 'base.html' %}

{% block content %}
{%if object%}
<h1> Edit <span class='teal-text'>{{object.name}}</span></h1>
{%else%}
<h1>Add Trail</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/trails/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Trail Details</h1>
<div class="row">
    <div class="col s6">
<div class="card">
    
    <div class="cared-content">
        <span class="card-title">{{ trail.name}}</span>
        <p>Terrian:{{trail.terrian}}</p>
        <p>Description:{{trail.description}}</p>
        {%if trail.length > 13 %}
        <p>Length: {{ trail.length}}</p>
        <p> Hint: Sholud preaperd for sleep over night</p>
        {% else %}
        <p>Hint: Short one day hiking</p>
        <p>Length: {{ trail.lenght}}</p>
            
        {% endif %}

    </div>
<div class="card-action">
    <a href="{% url 'trails_update' trail.id%}">Edit</a>
    <a href="{% url 'trails_delete' trail.id%}">Delete</a>
</div>
</div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_maintaining' trail.id %}"method="post">
            {% csrf_token %}
            {{ maintaining_form.as_p }}
            <input type="submit" class="btn" value="Add Maintaining">
          </form>
        <table class="striped">
        </thead>
        <tr><th>Date</th><th>Task</th></tr>
        <tbody>
            {%for maintaining in trail.maintaining_set.all %}
            <tr>
                <td>{{maintaining.date}}</td>
                <td>{{maintaining.get_task_display}}</td>
    
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
</div>
<script>
var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_task');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/trails/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Trail list</h1>
{% for trail in trails %}
<div class="card">
    <a href="{% url 'detail' trail.id %}">
    <div class="cared-content">
        <span class="card-title">{{ trail.name}}</span>
        <p>Terrian:{{trail.terrian}}</p>
        <p>Description:{{trail.description}}</p>
        {%if trail.length > 13 %}
        <p>Length: {{ trail.length}}</p>
        <p> Hint: Sholud preaperd for sleep over night</p>
        {% else %}
        <p>Hint: Short one day hiking</p>
        <p>Length: {{ trail.lenght}}</p>
            
        {% endif %}


    </div>
</a>
</div>
{% endfor %}
{% endblock %}